#! /bin/sh
set -e
agent=$1
rm -rf /tmp/gocd
mkdir /tmp/gocd
cp -r -f bootstrap /tmp/gocd/bootstrap

BOOTSTRAP=$([ ! -z $BOOTSTRAP_PATH ] && echo $BOOTSTRAP_PATH || echo "bootstrap.d" )
cp -r -f $BOOTSTRAP /tmp/gocd/bootstrap.d
chmod  777 /tmp/gocd/bootstrap.d/*

CONFIGS=$([ ! -z $CONFIGS_PATH ] && echo $CONFIGS_PATH || echo "configs" )
cp -r -f $CONFIGS /tmp/gocd/configs

DATA=$([ ! -z $DATA_PATH ] && echo $DATA_PATH || echo "data" )
cp -r -f $DATA /tmp/gocd/data

SCRIPTS=$([ ! -z $SCRIPTS_PATH ] && echo $SCRIPTS_PATH || echo "scripts" )
if [ -d "$SCRIPTS" ] && [ -d "$SCRIPTS/$agent" ]
then
    cp -r -f $SCRIPTS/$agent /tmp/gocd/scripts
else
    mkdir /tmp/gocd/scripts
fi
if [ -d "$SCRIPTS/common" ]
then
    if [ -f "$SCRIPTS/$agent/config" ]
    then
        for file in $(cat $SCRIPTS/$agent/config)
        do
            cp $SCRIPTS/common/$file /tmp/gocd/scripts
        done
        rm -f /tmp/gocd/scripts/config
    fi
fi
chmod  -R 777 /tmp/gocd/scripts

DOCKERFILE=$([ ! -z $DOCKERFILE_PATH ] && echo $DOCKERFILE_PATH || echo "Dockerfile" )
cp -r -f $DOCKERFILE /tmp/gocd/Dockerfile

cd /tmp/gocd
if hash podman
then
    export DOCKER_BINARY=podman
else
    export DOCKER_BINARY=docker
fi
$DOCKER_BINARY build -t stcarolas/gocd-agent-$agent --no-cache --build-arg AGENT_TYPE=$agent .
