format_version: 2

pipelines:
  PUBLISH_gocd_agents:
    group: GoCD
    label_template: ${code[:10]}
    materials:
      code:
        type: configrepo
        destination: code
    stages:
    - publish:
        jobs:
          gradle:
            elastic_profile_id: "docker"
            tasks:
              - script: |
                  cd code
                  sh deployment/publish.sh
